name: Create Release Tag on Version Change

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'manifest.json'

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This is required to push tags
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Get version from manifest
        id: get_version
        run: echo "version=$(jq -r .version manifest.json)" >> $GITHUB_OUTPUT

      - name: Create and push tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag "${{ steps.get_version.outputs.version }}"
          git push origin "${{ steps.get_version.outputs.version }}"
